### ISSUE TITLE
ShellCheck-0.7.2 fails to build with GHC-8.10.5

### ISSUE THREAD

**Issue by mouse07410** [koalaman/shellcheck#2250]
#### Fails to build
- Hackage version - ShellCheck 0.7.2
- MacOS BigSur 11.4, Xcode-12.5
- Haskell installed via `ghcup` 0.1.14.1
- GHC-8.10.5 (base 4.14.2.0), Cabal-3.4.0.0 (note: dynamic builds)

#### Excerpt from the build log

```sh
$ cabal install ShellCheck --overwrite-policy=always --disable-documentation
Resolving dependencies...
Build profile: -w ghc-8.10.5 -O1
In order, the following will be built (use -v for more details):
 - ShellCheck-0.7.2 (lib) (requires build)
 - ShellCheck-0.7.2 (exe:shellcheck) (requires build)
Starting     ShellCheck-0.7.2 (lib)
Building     ShellCheck-0.7.2 (lib)

Failed to build ShellCheck-0.7.2.
Build log ( /Users/ur20980/.cabal/logs/ghc-8.10.5/ShllChck-0.7.2-067e5d13.log
):
Configuring library for ShellCheck-0.7.2..
Preprocessing library for ShellCheck-0.7.2..
Building library for ShellCheck-0.7.2..
[ 1 of 23] Compiling Paths_ShellCheck ( dist/build/autogen/Paths_ShellCheck.hs, dist/build/Paths_ShellCheck.o, dist/build/Paths_ShellCheck.dyn_o )
[ 2 of 23] Compiling ShellCheck.Regex ( src/ShellCheck/Regex.hs, dist/build/ShellCheck/Regex.o, dist/build/ShellCheck/Regex.dyn_o )

src/ShellCheck/Regex.hs:54:13: warning: [-Wname-shadowing]
    This binding for ‘match’ shadows the existing binding
      imported from ‘Text.Regex.TDFA’ at src/ShellCheck/Regex.hs:28:1-22
      (and originally defined in ‘regex-base-0.94.0.1:Text.Regex.Base.RegexLike’)
   |
54 |         (_, match, rest, _) <- matchM re str :: Maybe (String, String, String, [String])
   |             ^^^^^

src/ShellCheck/Regex.hs:71:10: warning: [-Wname-shadowing]
    This binding for ‘before’ shadows the existing binding
      imported from ‘Text.Regex.TDFA’ at src/ShellCheck/Regex.hs:28:1-22
      (and originally defined in ‘regex-base-0.94.0.1:Text.Regex.Base.RegexLike’)
   |
71 |         (before, match, after) <- matchM re str :: Maybe (String, String, String)
   |          ^^^^^^

src/ShellCheck/Regex.hs:71:18: warning: [-Wname-shadowing]
    This binding for ‘match’ shadows the existing binding
      imported from ‘Text.Regex.TDFA’ at src/ShellCheck/Regex.hs:28:1-22
      (and originally defined in ‘regex-base-0.94.0.1:Text.Regex.Base.RegexLike’)
   |
71 |         (before, match, after) <- matchM re str :: Maybe (String, String, String)
   |                  ^^^^^

.  .  .  .  .

src/ShellCheck/Checks/Commands.hs:1147:1: warning: [-Wmissing-signatures]
    Top-level binding with no type signature:
      ShellCheck.Checks.Commands.runTests :: IO Bool
     |
1147 | runTests =  $( [| $(forAllProperties) (quickCheckWithResult (stdArgs { maxSuccess = 1 }) ) |])
     | ^^^^^^^^
[21 of 23] Compiling ShellCheck.Analytics ( src/ShellCheck/Analytics.hs, dist/build/ShellCheck/Analytics.o, dist/build/ShellCheck/Analytics.dyn_o )

src/ShellCheck/Analytics.hs:4158:13: error:
    parse error on input ‘-- $var==42’
     |
4158 |             -- $var==42
     |             ^^^^^^^^^^^
cabal: Failed to build ShellCheck-0.7.2 (which is required by exe:shellcheck
from ShellCheck-0.7.2). See the build log above for details.
```

#### Complete log

[shllchck-0.7.2.log.txt](https://github.com/koalaman/shellcheck/files/6635610/shllchck-0.7.2.log.txt)

**Comment by e-kwsm** [comment]
ShellCheck builds with 8.10 as tested in CI, so this seems to be fixed at some point.
